version: '3'

services:

  app:
    build: ./docker/php
    ports:
      - "8080:8080"
      - "9999:9999"
    restart: always
    container_name: wp_app
    working_dir: /var/www
    volumes:
      - ./sites:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sites:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/php.conf:/etc/nginx/php.conf
    restart: always