version: '3'

services:
  wp-app:
    build: ./x-docker/php
    ports:
      - 8080:8080
      - 9999:9999
    restart: always
    working_dir: /var/www
    volumes:
      - ./sites:/var/www
  webserver:
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./sites:/var/www
      - ./x-docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./x-docker/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    image: mysql:8.0
    restart: always
    command:
      - --character-set-server=utf8mb4
    environment:
      - name=value
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    restart: always
    ports:
      - "8888:80"